      SUBROUTINE DEBIEX(BUF,LBUF,IBUF)
C     DEBIEX IS THE EXECUTION PHASE OF SEISMIC PROCESS DEBIAS.  IT REMOVES THE
C DC COMPONENT OF EVERY TRACE.  ALL COMPUTATIONS ARE DONE IN THE AP.
C
C  WRITTEN AND COPYRIGHTED BY:
C  PAUL HENKART, SCRIPPS INSTITUTION OF OCEANOGRAPHY, 27 OCTOBER 1981
C  ALL RIGHTS ARE RESERVED BY THE AUTHOR.  PERMISSION TO COPY OR REPRODUCE THIS
C  SUBROUTINE, BY COMPUTER OR OTHER MEANS, MAY BE OBTAINED ONLY FROM THE AUTHOR.
C
      COMMON /SIOAP/ IASGND,IRELSE,IN,IOUT,NEXTAD,LAPSIZ,IFREE,IUSEAP
      COMMON /APMEM/ A(32766)
      COMMON /READT/ ILUN,NUMHDR
      DIMENSION BUF(111),LBUF(111),IBUF(111)
      INTEGER*2 IBUF
C
      NSAMPS=IBUF(58)
      IF(IUSEAP.EQ.0) GO TO 100
      CALL INAP(BUF(NUMHDR+1),NSAMPS)
      CALL DEMEAN(IN,IN,NSAMPS,NEXTAD)
      RETURN
  100 IF(IN.NE.0) GO TO 200
      CALL DEBIAS(BUF(NUMHDR+1),BUF(NUMHDR+1),NSAMPS)
      RETURN
  200 CALL DEBIAS(A(IN),A(IN),NSAMPS)
      RETURN
      END
