      SUBROUTINE STKSE(INWIN,ISTKWN,IENERG,NSAMPS,IDIV)
C   STKSE IS THE HOST VERSION OF STKSEM, WHICH CALCULATES THE MEAN ENERGY
C  OF A BUNCH OF TRACES AS WELL AS FORMING A STACKED TRACE.
C
C COPYRIGHTED BY PAUL HENKART 23 JANUARY 1983
C
C ARGUMENTS:
C INWIN - THE INDEX OF APMEM OF THE BEGINNING OF THE WINDOW TO STACK.
C ISTKWN - THE INDEX OF APMEM OF WHERE THE STACKED WINDOW STARTS.
C IENERG - THE INDEX OF APMEM OF WHERE TO PUT THE ENERGY OF THE INPUT WINDOW.
C NSAMPS - THE NUMBER OF SAMPLES IN THE WINDOW.
C IDIV   - THE INDEX OF A WORD IN APMEM THAT IS THE COUNT OF WINDOWS (I.E. ADD
C          TO IT)
C
       COMMON /APMEM/ A(32766)
C
      J=INWIN-1
      K=ISTKWN-1
      ENERGY=0.
      DO 100 I=1,NSAMPS
      A(K+I)=A(K+I)+A(J+I)                                              /* STACK THE WINDOW
100   ENERGY=ENERGY+A(J+I)*A(J+I)
      A(IENERG)=A(IENERG)+ENERGY
      A(IDIV)=A(IDIV)+1.
c      PRINT 111,J,K,IENERG,IDIV,A(IENERG),A(IDIV)
c111   FORMAT(' IN STKSE',4I8,2F12.5)
      RETURN
      END

