      SUBROUTINE SWAP32(BUF,N)
C     SWAP32 SWAPS THE 4 BYTES WITHIN EACH 32 BIT WORD OF ARRAY BUF.
C  THIS ROUTINE IS USEFUL FOR CONVERTING DEC 32 BIT INTEGERS TO OTHER COMPUTER
C  INTEGER FORMATS (OR VICE VERSA).
C
C  ARGUMENTS:
C     BUF - THE ARRAY TO BE CONVERTED.
C     N   - THE NUMBER OF 32 BIT WORDS TO BE CONVERTED. INTEGER*4
C
C  COPYRIGHT: PAUL HENKART, SCRIPPS INSTITUTION OF OCEANOGRAPHY, 11 APRIL 1982
C
      CHARACTER*1 BUF(1),A(4)
C
      J=1
      DO 200 I=1,N
      A(1)=BUF(J)
      A(2)=BUF(J+1)
      A(3)=BUF(J+2)
      A(4)=BUF(J+3)
      BUF(J)=A(4)
      BUF(J+1)=A(3)
      BUF(J+2)=A(2)
      BUF(J+3)=A(1)
  200 J=J+4
      RETURN
      END
