      SUBROUTINE SWAP64(BUF,N)
C     SWAP64 SWAPS THE 8 BYTES WITHIN EACH 64 BIT WORD OF ARRAY BUF.
C  THIS ROUTINE IS USEFUL FOR CONVERTING LITTLE ENDIAN (E.G> INTEL)
C  64 BIT DOUBLE PRECISION IEEE WORDS TO BIG ENDIAN (E.G. SUN) ORDER.
C
C  ARGUMENTS:
C     BUF - THE ARRAY TO BE CONVERTED.
C     N   - THE NUMBER OF 64 BIT WORDS TO BE CONVERTED. INTEGER*4
C
C  COPYRIGHT: PAUL HENKART, SCRIPPS INSTITUTION OF OCEANOGRAPHY
C
      CHARACTER*1 BUF(1),A(8)
C
      J=1
      DO 200 I=1,N
      A(1)=BUF(J)
      A(2)=BUF(J+1)
      A(3)=BUF(J+2)
      A(4)=BUF(J+3)
      A(5)=BUF(J+4)
      A(6)=BUF(J+5)
      A(7)=BUF(J+6)
      A(8)=BUF(J+7)
      BUF(J)=A(8)
      BUF(J+1)=A(7)
      BUF(J+2)=A(6)
      BUF(J+3)=A(5)
      BUF(J+4)=A(4)
      BUF(J+5)=A(3)
      BUF(J+6)=A(2)
      BUF(J+7)=A(1)
  200 J=J+8
      RETURN
      END
